# Задание 1

In [ ]:
import pandas as pd
import numpy as np

In [486]:
def d(a, i, j, k, s):
    if (s == '-'):
        a[i - 1, :] -= k * a[j - 1, :]
    if (s == '+'):
        a[i - 1, :] += k * a[j - 1, :]
    print('& \\alpha_1 & \\alpha_2 & \\alpha_3 & \\alpha_4 & \\cr')
    for i in range(len(a[:, 0])):
        print(' & ', end='')
        for j in range(len(a[0, :]) - 1):
            print(a[i, j], end=' & ')
        print(a[i, len(a[0, :] ) - 1], '\\cr', sep=' ')
    print('--------------------------')
    return

def s(a, i, j):
    temp = np.array(a[i - 1, :])
    a[i - 1, :] = np.array(a[j - 1, :])
    a[j - 1, :] = temp
    print('& \\alpha_1 & \\alpha_2 & \\alpha_3 & \\alpha_4 & \\cr')
    for i in range(len(a[:, 0])):
        print(' & ', end='')
        for j in range(len(a[0, :]) - 1):
            print(a[i, j], end=' & ')
        print(a[i, len(a[0, :] ) - 1], '\\cr', sep=' ')
    print('--------------------------')
    return

In [299]:
a = np.array([[-26, 1, 7, -47, 4],
              [-13, -4, -1, 35, 2],
              [-29, -9, 4, 16, -5],
              [42, 6, -2, -40, -9]
             ])

In [300]:
print(a)

[[-26   1   7 -47   4]
 [-13  -4  -1  35   2]
 [-29  -9   4  16  -5]
 [ 42   6  -2 -40  -9]]


In [301]:
d(a, 4, 2, 1, '+')
d(a, 4, 3, 1, '+')

-26 & 1 & 7 & -47 & 4
-13 & -4 & -1 & 35 & 2
-29 & -9 & 4 & 16 & -5
29 & 2 & -3 & -5 & -7
--------------------------
-26 & 1 & 7 & -47 & 4
-13 & -4 & -1 & 35 & 2
-29 & -9 & 4 & 16 & -5
0 & -7 & 1 & 11 & -12
--------------------------


In [302]:
d(a, 1, 2, 2, '-')

0 & 9 & 9 & -117 & 0
-13 & -4 & -1 & 35 & 2
-29 & -9 & 4 & 16 & -5
0 & -7 & 1 & 11 & -12
--------------------------


In [303]:
s(a, 1, 2)
s(a, 2, 3)

-13 & -4 & -1 & 35 & 2
0 & 9 & 9 & -117 & 0
-29 & -9 & 4 & 16 & -5
0 & -7 & 1 & 11 & -12
--------------------------
--------------------------
-13 & -4 & -1 & 35 & 2
-29 & -9 & 4 & 16 & -5
0 & 9 & 9 & -117 & 0
0 & -7 & 1 & 11 & -12
--------------------------
--------------------------


In [304]:
d(a, 2, 1, 2, '-')

-13 & -4 & -1 & 35 & 2
-3 & -1 & 6 & -54 & -9
0 & 9 & 9 & -117 & 0
0 & -7 & 1 & 11 & -12
--------------------------


In [305]:
d(a, 1, 2, 4, '-')

-1 & 0 & -25 & 251 & 38
-3 & -1 & 6 & -54 & -9
0 & 9 & 9 & -117 & 0
0 & -7 & 1 & 11 & -12
--------------------------


In [306]:
d(a, 2, 1, 3, '-')

-1 & 0 & -25 & 251 & 38
0 & -1 & 81 & -807 & -123
0 & 9 & 9 & -117 & 0
0 & -7 & 1 & 11 & -12
--------------------------


In [307]:
d(a, 3, 2, 9, '+')

-1 & 0 & -25 & 251 & 38
0 & -1 & 81 & -807 & -123
0 & 0 & 738 & -7380 & -1107
0 & -7 & 1 & 11 & -12
--------------------------


In [308]:
d(a, 4, 2, 7, '-')

-1 & 0 & -25 & 251 & 38
0 & -1 & 81 & -807 & -123
0 & 0 & 738 & -7380 & -1107
0 & 0 & -566 & 5660 & 849
--------------------------


In [309]:
d(a, 3, 4, 1, '+')

-1 & 0 & -25 & 251 & 38
0 & -1 & 81 & -807 & -123
0 & 0 & 172 & -1720 & -258
0 & 0 & -566 & 5660 & 849
--------------------------


In [310]:
d(a, 4, 3, 3, '+')

-1 & 0 & -25 & 251 & 38
0 & -1 & 81 & -807 & -123
0 & 0 & 172 & -1720 & -258
0 & 0 & -50 & 500 & 75
--------------------------


In [311]:
d(a, 3, 4, 3, '+')

-1 & 0 & -25 & 251 & 38
0 & -1 & 81 & -807 & -123
0 & 0 & 22 & -220 & -33
0 & 0 & -50 & 500 & 75
--------------------------


In [312]:
d(a, 4, 3, 2, '+')

-1 & 0 & -25 & 251 & 38
0 & -1 & 81 & -807 & -123
0 & 0 & 22 & -220 & -33
0 & 0 & -6 & 60 & 9
--------------------------


In [313]:
d(a, 3, 4, 4, '+')

-1 & 0 & -25 & 251 & 38
0 & -1 & 81 & -807 & -123
0 & 0 & -2 & 20 & 3
0 & 0 & -6 & 60 & 9
--------------------------


In [314]:
d(a, 4, 3, 3, '-')

-1 & 0 & -25 & 251 & 38
0 & -1 & 81 & -807 & -123
0 & 0 & -2 & 20 & 3
0 & 0 & 0 & 0 & 0
--------------------------


In [315]:
d(a, 2, 3, 40, '+')

-1 & 0 & -25 & 251 & 38
0 & -1 & 1 & -7 & -3
0 & 0 & -2 & 20 & 3
0 & 0 & 0 & 0 & 0
--------------------------


In [316]:
d(a, 1, 3, 12, '-')

-1 & 0 & -1 & 11 & 2
0 & -1 & 1 & -7 & -3
0 & 0 & -2 & 20 & 3
0 & 0 & 0 & 0 & 0
--------------------------


In [317]:
d(a, 1, 3, 1, '-')

-1 & 0 & 1 & -9 & -1
0 & -1 & 1 & -7 & -3
0 & 0 & -2 & 20 & 3
0 & 0 & 0 & 0 & 0
--------------------------


# Задание 2

In [318]:
b = np.array([[-34, -26, -152, 10],
              [-4, 7, -38, -29],
              [-16, -19, -58, 25],
              [-3, -5, -8, 9]
             ])

In [319]:
print(b)

[[ -34  -26 -152   10]
 [  -4    7  -38  -29]
 [ -16  -19  -58   25]
 [  -3   -5   -8    9]]


In [320]:
d(b, 1, 3, 2, '-')

-2 & 12 & -36 & -40
-4 & 7 & -38 & -29
-16 & -19 & -58 & 25
-3 & -5 & -8 & 9
--------------------------


In [321]:
d(b, 3, 2, 4, '-')

-2 & 12 & -36 & -40
-4 & 7 & -38 & -29
0 & -47 & 94 & 141
-3 & -5 & -8 & 9
--------------------------


In [322]:
d(b, 2, 1, 2, '-')

-2 & 12 & -36 & -40
0 & -17 & 34 & 51
0 & -47 & 94 & 141
-3 & -5 & -8 & 9
--------------------------


In [323]:
d(b, 1, 4, 1, '-')

1 & 17 & -28 & -49
0 & -17 & 34 & 51
0 & -47 & 94 & 141
-3 & -5 & -8 & 9
--------------------------


In [324]:
d(b, 4, 1, 3, '+')

1 & 17 & -28 & -49
0 & -17 & 34 & 51
0 & -47 & 94 & 141
0 & 46 & -92 & -138
--------------------------


In [325]:
d(b, 3, 4, 1, '+')

1 & 17 & -28 & -49
0 & -17 & 34 & 51
0 & -1 & 2 & 3
0 & 46 & -92 & -138
--------------------------


In [326]:
d(b, 2, 3, 17, '-')

1 & 17 & -28 & -49
0 & 0 & 0 & 0
0 & -1 & 2 & 3
0 & 46 & -92 & -138
--------------------------


In [327]:
d(b, 4, 3, 46, '+')

1 & 17 & -28 & -49
0 & 0 & 0 & 0
0 & -1 & 2 & 3
0 & 0 & 0 & 0
--------------------------


In [328]:
d(b, 1, 3, 17, '+')

1 & 0 & 6 & 2
0 & 0 & 0 & 0
0 & -1 & 2 & 3
0 & 0 & 0 & 0
--------------------------


# Задание 3

In [347]:
c = np.array([
        [-4, -6, -7, 0],
        [0, -1, -3, -4],
        [-8, -11, -11, 4],
        [-4, -4, -1, 8]
    ])

In [348]:
print(c)

[[ -4  -6  -7   0]
 [  0  -1  -3  -4]
 [ -8 -11 -11   4]
 [ -4  -4  -1   8]]


In [349]:
d(c, 1, 2, 0, '+')

-4 & -6 & -7 & 0 \\
0 & -1 & -3 & -4 \\
-8 & -11 & -11 & 4 \\
-4 & -4 & -1 & 8 \\
--------------------------


In [350]:
d(c, 3, 1, 2, '-')

-4 & -6 & -7 & 0 \\
0 & -1 & -3 & -4 \\
0 & 1 & 3 & 4 \\
-4 & -4 & -1 & 8 \\
--------------------------


In [351]:
d(c, 4, 1, 1, '-')

-4 & -6 & -7 & 0 \\
0 & -1 & -3 & -4 \\
0 & 1 & 3 & 4 \\
0 & 2 & 6 & 8 \\
--------------------------


In [352]:
d(c, 2, 3, 1, '+')

-4 & -6 & -7 & 0 \\
0 & 0 & 0 & 0 \\
0 & 1 & 3 & 4 \\
0 & 2 & 6 & 8 \\
--------------------------


In [353]:
d(c, 4, 3, 2, '-')

-4 & -6 & -7 & 0 \\
0 & 0 & 0 & 0 \\
0 & 1 & 3 & 4 \\
0 & 0 & 0 & 0 \\
--------------------------


In [354]:
e = np.array([
        [8, 12, 14, 0],
        [8, 11, 11, -4],
        [8, 13, 17, 4],
        [-8, -10, -8, 8]
    ])

In [355]:
print(e)

[[  8  12  14   0]
 [  8  11  11  -4]
 [  8  13  17   4]
 [ -8 -10  -8   8]]


In [356]:
d(e, 1, 2, 0, '+')

8 & 12 & 14 & 0 \\
8 & 11 & 11 & -4 \\
8 & 13 & 17 & 4 \\
-8 & -10 & -8 & 8 \\
--------------------------


In [358]:
d(e, 4, 1, 1, '+')

8 & 12 & 14 & 0 \\
8 & 11 & 11 & -4 \\
8 & 13 & 17 & 4 \\
0 & 2 & 6 & 8 \\
--------------------------


In [359]:
d(e, 3, 1, 1, '-')

8 & 12 & 14 & 0 \\
8 & 11 & 11 & -4 \\
0 & 1 & 3 & 4 \\
0 & 2 & 6 & 8 \\
--------------------------


In [360]:
d(e, 2, 1, 1, '-')

8 & 12 & 14 & 0 \\
0 & -1 & -3 & -4 \\
0 & 1 & 3 & 4 \\
0 & 2 & 6 & 8 \\
--------------------------


In [361]:
d(e, 4, 3, 2, '-')

8 & 12 & 14 & 0 \\
0 & -1 & -3 & -4 \\
0 & 1 & 3 & 4 \\
0 & 0 & 0 & 0 \\
--------------------------


In [362]:
d(e, 3, 2, 1, '+')

8 & 12 & 14 & 0 \\
0 & -1 & -3 & -4 \\
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 \\
--------------------------


In [363]:
f = np.array([
        [-4, -6, -7, 0],
        [0, 1, 3, 4],
        [8, 12, 14, 0],
        [0, -1, -3, -4]
    ])

In [364]:
print(f)

[[-4 -6 -7  0]
 [ 0  1  3  4]
 [ 8 12 14  0]
 [ 0 -1 -3 -4]]


In [365]:
d(f, 1, 2, 0, '+')

-4 & -6 & -7 & 0 \\
0 & 1 & 3 & 4 \\
8 & 12 & 14 & 0 \\
0 & -1 & -3 & -4 \\
--------------------------


In [366]:
d(f, 3, 1, 2, '+')

-4 & -6 & -7 & 0 \\
0 & 1 & 3 & 4 \\
0 & 0 & 0 & 0 \\
0 & -1 & -3 & -4 \\
--------------------------


In [367]:
d(f, 4, 2, 1, '+')

-4 & -6 & -7 & 0 \\
0 & 1 & 3 & 4 \\
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 \\
--------------------------


In [368]:
a = np.array([
        [-4, 0, 8, 0],
        [-6, 1, 12, -1],
        [-7, 3, 14, -3],
        [0, 4, 0, -4]
    ])

In [369]:
print(a)

[[-4  0  8  0]
 [-6  1 12 -1]
 [-7  3 14 -3]
 [ 0  4  0 -4]]


In [370]:
d(a, 2, 3, 1, '-')

-4 & 0 & 8 & 0 \\
1 & -2 & -2 & 2 \\
-7 & 3 & 14 & -3 \\
0 & 4 & 0 & -4 \\
--------------------------


In [371]:
d(a, 1, 2, 4, '+')

0 & -8 & 0 & 8 \\
1 & -2 & -2 & 2 \\
-7 & 3 & 14 & -3 \\
0 & 4 & 0 & -4 \\
--------------------------


In [372]:
d(a, 3, 2, 7, '+')

0 & -8 & 0 & 8 \\
1 & -2 & -2 & 2 \\
0 & -11 & 0 & 11 \\
0 & 4 & 0 & -4 \\
--------------------------


In [378]:
s(a, 1, 2)

0 & -8 & 0 & 8 \\
1 & -2 & -2 & 2 \\
0 & -11 & 0 & 11 \\
0 & 4 & 0 & -4 \\
--------------------------


# Задание 4

In [452]:
b = np.array([
        [10, -16, -10, 19],
        [-2, 18, 19, -7],
        [15, -2, 10, 3],
        [-2, 25, 24, -10]
    ])

In [453]:
print(b)

[[ 10 -16 -10  19]
 [ -2  18  19  -7]
 [ 15  -2  10   3]
 [ -2  25  24 -10]]


In [454]:
d(b, 1, 2, 0, '+')

10 & -16 & -10 & 19 \\
-2 & 18 & 19 & -7 \\
15 & -2 & 10 & 3 \\
-2 & 25 & 24 & -10 \\
--------------------------


In [455]:
d(b, 3, 1, 1, '-')

10 & -16 & -10 & 19 \\
-2 & 18 & 19 & -7 \\
5 & 14 & 20 & -16 \\
-2 & 25 & 24 & -10 \\
--------------------------


In [456]:
d(b, 1, 3, 2, '-')

0 & -44 & -50 & 51 \\
-2 & 18 & 19 & -7 \\
5 & 14 & 20 & -16 \\
-2 & 25 & 24 & -10 \\
--------------------------


In [457]:
d(b, 4, 2, 1, '-')

0 & -44 & -50 & 51 \\
-2 & 18 & 19 & -7 \\
5 & 14 & 20 & -16 \\
0 & 7 & 5 & -3 \\
--------------------------


In [458]:
d(b, 3, 2, 2, '+')

0 & -44 & -50 & 51 \\
-2 & 18 & 19 & -7 \\
1 & 50 & 58 & -30 \\
0 & 7 & 5 & -3 \\
--------------------------


In [459]:
d(b, 2, 3, 2, '+')

0 & -44 & -50 & 51 \\
0 & 118 & 135 & -67 \\
1 & 50 & 58 & -30 \\
0 & 7 & 5 & -3 \\
--------------------------


In [460]:
s(b, 1, 3)

1 & 50 & 58 & -30 \\
0 & 118 & 135 & -67 \\
0 & -44 & -50 & 51 \\
0 & 7 & 5 & -3 \\
--------------------------


In [461]:
d(b, 2, 3, 2, '+')

1 & 50 & 58 & -30 \\
0 & 30 & 35 & 35 \\
0 & -44 & -50 & 51 \\
0 & 7 & 5 & -3 \\
--------------------------


In [462]:
d(b, 3, 2, 1, '+')

1 & 50 & 58 & -30 \\
0 & 30 & 35 & 35 \\
0 & -14 & -15 & 86 \\
0 & 7 & 5 & -3 \\
--------------------------


In [463]:
d(b, 3, 4, 2, '+')

1 & 50 & 58 & -30 \\
0 & 30 & 35 & 35 \\
0 & 0 & -5 & 80 \\
0 & 7 & 5 & -3 \\
--------------------------


In [464]:
d(b, 2, 4, 4, '-')

1 & 50 & 58 & -30 \\
0 & 2 & 15 & 47 \\
0 & 0 & -5 & 80 \\
0 & 7 & 5 & -3 \\
--------------------------


In [465]:
d(b, 4, 2, 3, '-')

1 & 50 & 58 & -30 \\
0 & 2 & 15 & 47 \\
0 & 0 & -5 & 80 \\
0 & 1 & -40 & -144 \\
--------------------------


In [466]:
d(b, 2, 4, 2, '-')

1 & 50 & 58 & -30 \\
0 & 0 & 95 & 335 \\
0 & 0 & -5 & 80 \\
0 & 1 & -40 & -144 \\
--------------------------


In [467]:
s(b, 2, 4)

1 & 50 & 58 & -30 \\
0 & 1 & -40 & -144 \\
0 & 0 & -5 & 80 \\
0 & 0 & 95 & 335 \\
--------------------------


In [469]:
d(b, 4, 3, 19, '+')

1 & 50 & 58 & -30 \\
0 & 1 & -40 & -144 \\
0 & 0 & -5 & 80 \\
0 & 0 & 0 & 1855 \\
--------------------------


In [434]:
d(b, 2, 4, 3, '+')

1 & 50 & 58 & -30 \\
0 & 7 & 5 & -3 \\
0 & 0 & -5 & 80 \\
0 & 2 & 15 & 47 \\
--------------------------


In [487]:
a = np.array([
        [10, -2, 15, -2, 25],
        [-16, 18, -2, 25, -18],
        [-10, 19, 10, 24, 0],
        [19, -7, 3, -10, 22]
    ])

In [488]:
print(a)

[[ 10  -2  15  -2  25]
 [-16  18  -2  25 -18]
 [-10  19  10  24   0]
 [ 19  -7   3 -10  22]]


In [489]:
d(a, 1, 2, 0, '+')

& \alpha_1 & \alpha_2 & \alpha_3 & \alpha_4 & \cr
 & 10 & -2 & 15 & -2 & 25 \cr
 & -16 & 18 & -2 & 25 & -18 \cr
 & -10 & 19 & 10 & 24 & 0 \cr
 & 19 & -7 & 3 & -10 & 22 \cr
--------------------------


In [490]:
d(a, 3, 1, 1, '+')

& \alpha_1 & \alpha_2 & \alpha_3 & \alpha_4 & \cr
 & 10 & -2 & 15 & -2 & 25 \cr
 & -16 & 18 & -2 & 25 & -18 \cr
 & 0 & 17 & 25 & 22 & 25 \cr
 & 19 & -7 & 3 & -10 & 22 \cr
--------------------------


In [491]:
d(a, 4, 1, 2, '-')

& \alpha_1 & \alpha_2 & \alpha_3 & \alpha_4 & \cr
 & 10 & -2 & 15 & -2 & 25 \cr
 & -16 & 18 & -2 & 25 & -18 \cr
 & 0 & 17 & 25 & 22 & 25 \cr
 & -1 & -3 & -27 & -6 & -28 \cr
--------------------------


In [492]:
d(a, 1, 4, 10, '+')

& \alpha_1 & \alpha_2 & \alpha_3 & \alpha_4 & \cr
 & 0 & -32 & -255 & -62 & -255 \cr
 & -16 & 18 & -2 & 25 & -18 \cr
 & 0 & 17 & 25 & 22 & 25 \cr
 & -1 & -3 & -27 & -6 & -28 \cr
--------------------------


In [493]:
d(a, 2, 4, 16, '-')

& \alpha_1 & \alpha_2 & \alpha_3 & \alpha_4 & \cr
 & 0 & -32 & -255 & -62 & -255 \cr
 & 0 & 66 & 430 & 121 & 430 \cr
 & 0 & 17 & 25 & 22 & 25 \cr
 & -1 & -3 & -27 & -6 & -28 \cr
--------------------------


In [494]:
s(a, 1, 4)

& \alpha_1 & \alpha_2 & \alpha_3 & \alpha_4 & \cr
 & -1 & -3 & -27 & -6 & -28 \cr
 & 0 & 66 & 430 & 121 & 430 \cr
 & 0 & 17 & 25 & 22 & 25 \cr
 & 0 & -32 & -255 & -62 & -255 \cr
--------------------------


In [495]:
d(a, 2, 4, 2, '+')

& \alpha_1 & \alpha_2 & \alpha_3 & \alpha_4 & \cr
 & -1 & -3 & -27 & -6 & -28 \cr
 & 0 & 2 & -80 & -3 & -80 \cr
 & 0 & 17 & 25 & 22 & 25 \cr
 & 0 & -32 & -255 & -62 & -255 \cr
--------------------------


In [496]:
d(a, 4, 3, 2, '+')

& \alpha_1 & \alpha_2 & \alpha_3 & \alpha_4 & \cr
 & -1 & -3 & -27 & -6 & -28 \cr
 & 0 & 2 & -80 & -3 & -80 \cr
 & 0 & 17 & 25 & 22 & 25 \cr
 & 0 & 2 & -205 & -18 & -205 \cr
--------------------------


In [497]:
d(a, 4, 2, 1, '-')

& \alpha_1 & \alpha_2 & \alpha_3 & \alpha_4 & \cr
 & -1 & -3 & -27 & -6 & -28 \cr
 & 0 & 2 & -80 & -3 & -80 \cr
 & 0 & 17 & 25 & 22 & 25 \cr
 & 0 & 0 & -125 & -15 & -125 \cr
--------------------------


In [498]:
d(a, 3, 2, 9, '-')

& \alpha_1 & \alpha_2 & \alpha_3 & \alpha_4 & \cr
 & -1 & -3 & -27 & -6 & -28 \cr
 & 0 & 2 & -80 & -3 & -80 \cr
 & 0 & -1 & 745 & 49 & 745 \cr
 & 0 & 0 & -125 & -15 & -125 \cr
--------------------------


In [499]:
d(a, 2, 3, 2, '+')

& \alpha_1 & \alpha_2 & \alpha_3 & \alpha_4 & \cr
 & -1 & -3 & -27 & -6 & -28 \cr
 & 0 & 0 & 1410 & 95 & 1410 \cr
 & 0 & -1 & 745 & 49 & 745 \cr
 & 0 & 0 & -125 & -15 & -125 \cr
--------------------------


In [500]:
s(a, 2, 3)

& \alpha_1 & \alpha_2 & \alpha_3 & \alpha_4 & \cr
 & -1 & -3 & -27 & -6 & -28 \cr
 & 0 & -1 & 745 & 49 & 745 \cr
 & 0 & 0 & 1410 & 95 & 1410 \cr
 & 0 & 0 & -125 & -15 & -125 \cr
--------------------------


In [501]:
d(a, 3, 4, 12, '+')

& \alpha_1 & \alpha_2 & \alpha_3 & \alpha_4 & \cr
 & -1 & -3 & -27 & -6 & -28 \cr
 & 0 & -1 & 745 & 49 & 745 \cr
 & 0 & 0 & -90 & -85 & -90 \cr
 & 0 & 0 & -125 & -15 & -125 \cr
--------------------------


In [502]:
d(a, 4, 3, 1, '-')

& \alpha_1 & \alpha_2 & \alpha_3 & \alpha_4 & \cr
 & -1 & -3 & -27 & -6 & -28 \cr
 & 0 & -1 & 745 & 49 & 745 \cr
 & 0 & 0 & -90 & -85 & -90 \cr
 & 0 & 0 & -35 & 70 & -35 \cr
--------------------------


In [503]:
d(a, 3, 4, 3, '-')

& \alpha_1 & \alpha_2 & \alpha_3 & \alpha_4 & \cr
 & -1 & -3 & -27 & -6 & -28 \cr
 & 0 & -1 & 745 & 49 & 745 \cr
 & 0 & 0 & 15 & -295 & 15 \cr
 & 0 & 0 & -35 & 70 & -35 \cr
--------------------------


In [504]:
d(a, 4, 3, 2, '+')

& \alpha_1 & \alpha_2 & \alpha_3 & \alpha_4 & \cr
 & -1 & -3 & -27 & -6 & -28 \cr
 & 0 & -1 & 745 & 49 & 745 \cr
 & 0 & 0 & 15 & -295 & 15 \cr
 & 0 & 0 & -5 & -520 & -5 \cr
--------------------------


In [505]:
d(a, 3, 4, 3, '+')

& \alpha_1 & \alpha_2 & \alpha_3 & \alpha_4 & \cr
 & -1 & -3 & -27 & -6 & -28 \cr
 & 0 & -1 & 745 & 49 & 745 \cr
 & 0 & 0 & 0 & -1855 & 0 \cr
 & 0 & 0 & -5 & -520 & -5 \cr
--------------------------


In [506]:
s(a, 3, 4)

& \alpha_1 & \alpha_2 & \alpha_3 & \alpha_4 & \cr
 & -1 & -3 & -27 & -6 & -28 \cr
 & 0 & -1 & 745 & 49 & 745 \cr
 & 0 & 0 & -5 & -520 & -5 \cr
 & 0 & 0 & 0 & -1855 & 0 \cr
--------------------------


In [507]:
d(a, 2, 3, 149, '+')

& \alpha_1 & \alpha_2 & \alpha_3 & \alpha_4 & \cr
 & -1 & -3 & -27 & -6 & -28 \cr
 & 0 & -1 & 0 & -77431 & 0 \cr
 & 0 & 0 & -5 & -520 & -5 \cr
 & 0 & 0 & 0 & -1855 & 0 \cr
--------------------------


In [508]:
d(a, 1, 2, 3, '-')

& \alpha_1 & \alpha_2 & \alpha_3 & \alpha_4 & \cr
 & -1 & 0 & -27 & 232287 & -28 \cr
 & 0 & -1 & 0 & -77431 & 0 \cr
 & 0 & 0 & -5 & -520 & -5 \cr
 & 0 & 0 & 0 & -1855 & 0 \cr
--------------------------


In [510]:
d(a, 1, 3, 5, '-')

& \alpha_1 & \alpha_2 & \alpha_3 & \alpha_4 & \cr
 & -1 & 0 & -2 & 234887 & -3 \cr
 & 0 & -1 & 0 & -77431 & 0 \cr
 & 0 & 0 & -5 & -520 & -5 \cr
 & 0 & 0 & 0 & -1855 & 0 \cr
--------------------------
